---
# tasks file for roles/app_lb
- name: Creating load balancer for web servers
  elb_application_lb:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    name: "{{lb_name}}"
    region: "{{region}}"
#    access_logs_enabled: yes
#    access_logs_s3_bucket: "{{s3_url.name}}"
#    access_logs_s3_prefix: "logs"
    security_groups: "{{web_sg.group_id}}"
    subnets:
    - "{{output1.subnet.id}}"
    - "{{output2.subnet.id}}"
    listeners:
    - Protocol: HTTP
      Port: 80
      DefaultActions:
      - Type: forward
        TargetGroupName: "{{target_group_name}}"
    state: present
  register: elb
- name: print elb
  debug:
   var: elb    
