- name: Download JBoss from wildfly
  get_url:
    url: https://download.jboss.org/wildfly/15.0.1.Final/wildfly-15.0.1.Final.zip
    owner: jboss
    group: jboss
    dest: /opt/wildfly_jboss

- name: Extract archive
  unarchive:
    dest: /opt/wildfly_jboss
    src: /opt/wildfly_jboss/wildfly-15.0.1.Final.zip
    owner: jboss
    group: jboss
    copy: no
- name: Remove jboss archived files
  file:
    path: /opt/wildfly_jboss/wildfly-15.0.1.Final.zip
    state: absent
- debug: var=ansible_eth0.ipv4.address
- name: Updating bind address for jboss in Standalone.xml file
  replace:
   path: /opt/wildfly_jboss/wildfly-15.0.1.Final/standalone/configuration/standalone.xml
   regexp: '127.0.0.1'
   replace: "{{item}}"
   owner: jboss
   group: jboss
   mode: 0644
  with_items:
  - "{{ansible_eth0.ipv4.address}}"
- name: Set JBoss HOME
  lineinfile: dest=~/.bash_profile regexp='^JBOSS_HOME'>
              line="export JBOSS_HOME=/opt/wildfly_jboss/wildfly-15.0.1.Final"
              state=present
- name: Source Bashrc
  action: shell source ~/.bash_profile
