---
- import_playbook: playbooks/vpc_setup.yml
- import_playbook: playbooks/create_ec2_keypair
- import_playbook: playbooks/appserver_setup.yml
- import_playbook: playbooks/application_lb.yml
- import_playbook: playbooks/route53.yml
