---
# tasks file for roles/db_security_group
- name: Creating DB security group  
  ec2_group:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    name: "{{db_sg_name}}"
    tags: { "Name":"{{db_sg_name}}" }
    description: "{{db_sg_desc}}"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{region}}"
    rules:
      - proto: "{{db_protocol}}"
        ports:
        - "{{db_port_no}}"
        group_id: "{{app_sg.group_id}}"
        rule_desc: "{{db_sg_rule_desc}}"
  register: db_sg
