---
# tasks file for /etc/ansible/roles/vpc
- name: Creating "{{vpc_name}}" VPC
  ec2_vpc_net:
   aws_access_key: "{{aws_access_key}}"
   aws_secret_key: "{{aws_secret_key}}"
   name: "{{vpc_name}}"
   region: "{{region}}"
   dns_support: yes
   dns_hostnames: yes
   state: present
   cidr_block: "{{cidr_block}}"
   resource_tags: {"Environmet": "{{tag_env}}"}
  register: vpc
