---
# tasks file for roles/route53
- name: Creating route53
  route53:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    state: present
    command: create
    zone: "{{dns_name}}"
    record: "{{new_dns_name}}"
    type: A
    value: "{{elb.dns_name}}"
    alias: True
    alias_evaluate_target_health: True
    alias_hosted_zone_id: "{{elb.canonical_hosted_zone_id}}"
    overwrite: yes    
