---
- name: Installing application on jboss
  hosts: tag_Name_CICDAppServer*
  become: true
  user: ec2-user
  vars:
   ansible_ssh_private_key_file: /etc/ansible/ansible.pem
  roles:
  - roles/deploy_application_jboss
