---
- name: Creating db routetable
  hosts: webserver
  vars_files:
  - ../variables_file.yml
  tasks:
  - name: Creating db routetable
    include_role: 
     name: ../roles/routetable_dbserver
    vars:
      rt_name: "{{dbrt_name}}"
      destination: "{{ web_destination }}"
      subnet1_id: "{{ db1_subnet.subnet.id }}"
      subnet2_id: "{{ db2_subnet.subnet.id }}" 
      gateway_id: "{{ nat_gateway.nat_gateway_id }}"
