---
- name: Creating VPC 
  hosts: webserver
  become: true
  vars_files:
  - ../variables_file.yml
  tasks:
  - set_fact:
     cidr_block: "{{cidr_block}}"
     vpc_name: "{{vpc_name}}"
     region: "{{region}}"
     tag_env: "{{tag_env}}"
  roles:
  - ../roles/vpc 
