
---
- name: deleting VPC 
  hosts: webserver
  become: true
  vars_files:
  - ../variables_file.yml
  tasks:
   - name: Terminate EC2 instances
   - name: Delete Load balancer
   - name: Delete NAT gateway
   - name: Delete VPC peering
   - name: deleting "{{vpc_name}}" VPC
     ec2_vpc_net:
      name: "{{vpc_name}}"
      region: "{{region}}"
      state: absent
      cidr_block: "{{cidr_block}}"
